# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9feb432e622e95b7bca733b2cf52777c5e0654c3b817a655200c8ccbd4b3ff1d0648e476cfce2284f674f75e5c38ea820cb9b293856af3353bc83ddc0e419f89

test:
  secret_key_base: 4d71daa6438043e106aef6887fdf2a8a48f146b5d23dbfe63433d4df214b59516e5d0fe0d9670de5185ad95cedd00692bee11c2c600ffe00588a689fdfd57537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
